version: '3'
services:
  db:
    container_name: soccer-pg
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - soccer

  web:
    container_name: soccer-web
    image: valmirjunior/rails:1.0.1    
    working_dir: /rails/soccer
    volumes:
      - .:/rails/soccer
      - bundle_data:/usr/local/bundle
    command: /bin/sh
    tty: true
    ports:
      - "3000:3000"
    networks:
      - soccer

volumes:
  bundle_data:
  db_data:

networks:
  soccer:
    driver: bridge
